language: cpp
sudo: false

branches:
    only:
        - master

addons:
  apt:
    sources:
      - kubuntu-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - gcc-4.9
      - g++-4.9

before_script:
    - mkdir build && cd build
    - CXX=g++-4.9 CC=gcc-4.9 cmake ..

script:
    - CXX=g++-4.9 CC=gcc-4.9 cmake --build .
    - ctest -V
